WITH USERORDERS AS
	(SELECT SUM(O.ACCRUAL) AS ACCRUAL,
			O.USERID
		FROM PUBLIC.ORDERS O
		JOIN PUBLIC.STATUS S ON S."ID" = O."statusId"
		WHERE S."OrderStatus" = 'PROCESSED'
		GROUP BY O.USERID),
	USERWITHDRAWNS AS
	(SELECT SUM(W."pointsSum") AS WITHDRAWN,
			W.USERID
		FROM PUBLIC.WITHDRAWLS W
		GROUP BY W.USERID)
SELECT US.ACCRUAL,
	WS.WITHDRAWN
FROM USERORDERS US
left JOIN USERWITHDRAWNS WS ON WS.USERID = US.USERID
WHERE US.USERID = $1