SELECT SUM(O.ACCRUAL) AS ACCRUAL,
	SUM(W."pointsSum") AS WITHDRAWN
FROM PUBLIC.ORDERS O
JOIN PUBLIC.STATUS S ON S."ID" = O."statusId"
LEFT JOIN PUBLIC.WITHDRAWLS W ON W.USERID = O.USERID
WHERE O.USERID = $1
	AND S."OrderStatus" = 'PROCESSED' ;